### ISSUE TITLE
TestFailure Class

### ISSUE THREAD

**Issue by sihrc** [IndicoDataSolutions/IndicoIo-Java#7]
The tests in test failure class seem to all be testing multiapi calls. I don't think this is what we wanted. 
Do we need failure tests for each api / what would those look like?

Also what's serialVersionUID for again?
Also should we consider separating tests into classes for specific APIs

**Comment by Slater-Victoroff** [comment]
Yea... there's probably other ways that it makes sense to split up. They happen to be mostly on the MultiAPI stuff just because failures are the way we confirmed they weren't returning too much. Probably worth having a chat about how we should split up testing, just wanted to get something in place to stop the one massive test file.

**Comment by Slater-Victoroff** [comment]
serialVersionUID is so we don't get weird == behavior. It doesn't usually matter, but it's a good practice type thing that can very rarely lead to bugs that are a huge pain to track down.

**Comment by sihrc** [comment]
Opening a new issue for splitting tests.
